export const bgColorForType = {
  grass: "bg-grass",
  poison: "bg-poison",
  fire: "bg-fire",
  flying: "bg-gradient-to-b from-flying-top from-50% to-flying-bottom to-50%",
  water: "bg-water",
  bug: "bg-bug",
  normal: "bg-normal",
  electric: "bg-electric",
  fairy: "bg-fairy",
  ground: "bg-gradient-to-b from-ground-top from-50% to-ground-bottom to-50%",
  fighting: "bg-fighting",
  psychic: "bg-psychic",
  rock: "bg-rock",
  steel: "bg-steel",
  ice: "bg-ice",
  ghost: "bg-ghost",
  dragon: "bg-gradient-to-b from-dragon-top from-50% to-dragon-bottom to-50%",
  dark: "bg-dark",
};
